name: "Determine npm tag"
description: "Determine npm tag and whether the release is a prerelease"
author: "ajiho <lujiahao@88.com>"
runs:
  using: "composite"
  steps:
    - name: Run Determine npm dist-tag
      id: run-determine-npm-dist-tag
      shell: bash
      run: ${GITHUB_ACTION_PATH}/run.sh # or ${GITHUB_ACTION_PATH}
outputs:
  tag:
    description: "npm dist-tag"
    value: ${{ steps.run-determine-npm-dist-tag.outputs.tag }}
  prerelease:
    description: "prerelease flag"
    value: ${{ steps.run-determine-npm-dist-tag.outputs.prerelease }}
