name: "Determine npm tag"
description: "Determine npm tag and whether the release is a prerelease"
author: "ajiho <lujiahao@88.com>"
runs:
  using: "composite"
  steps:
    - name: Run dist tag script
      shell: bash
      run: |
        echo "Running entrypoint.sh"
        bash "$GITHUB_ACTION_PATH/entrypoint.sh"
outputs:
  tag:
    description: "The npm dist-tag to use when publishing"
  prerelease:
    description: "Whether this release is a prerelease"
